language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t stefanbogdan180394/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stefanbogdan180394/react-test npm test

after_success:
  - docker build -t stefanbogdan180394/multi-client ./client
  - docker build -t stefanbogdan180394/multi-nginx ./nginx
  - docker build -t stefanbogdan180394/multi-server ./server
  - docker build -t stefanbogdan180394/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker-hub
  - docker push stefanbogdan180394/multi-client
  - docker push stefanbogdan180394/multi-nginx
  - docker push stefanbogdan180394/multi-server
  - docker push stefanbogdan180394/multi-worker